---
grails:
    profile: web-plugin
    codegen:
        defaultPackage: grails.api.framework
info:
    app:
        name: api-framework
        version: 0.1.RC1
        grailsVersion: '@info.app.grailsVersion@'
spring:
    groovy:
        template:
            check-template-location: false

---
grails:
    mime:
        disable:
            accept:
                header:
                    userAgents:
                        - Gecko
                        - WebKit
                        - Presto
                        - Trident
        types:
            all: '*/*'
            atom: application/atom+xml
            css: text/css
            csv: text/csv
            form: application/x-www-form-urlencoded
            html: 
              - text/html
              - application/xhtml+xml
            js: text/javascript
            json:
              - application/json
              - text/json
            multipartForm: multipart/form-data
            rss: application/rss+xml
            text: text/plain
            hal: 
              - application/hal+json
              - application/hal+xml
            xml:
              - text/xml
              - application/xml
    urlmapping:
        cache:
            maxsize: 1000
    controllers:
        defaultScope: singleton
    converters:
        encoding: UTF-8
    views:
        default:
            codec: html
        gsp:
            encoding: UTF-8
            htmlcodec: xml
            codecs:
                expression: html
                scriptlets: html
                taglib: none
                staticparts: none
config:
    cache:
        name: 'ApiCache'
        eternal: false
        overflowToDisk: true
        maxElementsInMemory: 10000
        maxElementsOnDisk: 10000000
    cache:
        name: 'Trace'
        eternal: false
        overflowToDisk: true
        maxElementsInMemory: 1000
        maxElementsOnDisk: 10000
    cache:
        name: 'Limit'
        eternal: false
        overflowToDisk: true
        maxElementsInMemory: 1000
        maxElementsOnDisk: 10000

---
apitoolkit:
    apiName: 'api'
    attempts: 5
    roles: ['ROLE_USER','ROLE_ROOT','ROLE_ADMIN','ROLE_ARCH']
    profilerRoles: ['ROLE_ROOT','ROLE_ADMIN','ROLE_ARCH']
    apichain:
        limit: 3
    rest:
        postcrement: false
    chaining:
        enabled: true
    batching:
        enabled: true
    encoding: 'UTF-8'
    rateLimit:
        # NON-ADMIN ROLES; ADMINS HAVE NO LIMIT
        roles: ['ROLE_USER']
        # 15MIN/30MIN/60MIN
        check: '60MIN'
        limit: {'ROLE_USER':1000,'ROLE_ADMIN':100}
        sessionMaxInc: 50
    admin:
        roles: ['ROLE_ROOT','ROLE_ADMIN','ROLE_ARCH']
    serverType: 'master'
    webhook:
        services: ['iostate']
    corsConfig:
        includeEnvironments: ['development','test']
        excludeEnvironments: ['production']
        allowedOrigins: ['localhost:3000']

---
server:
    tomcat:
        backgroundProcessorDelay: 30
        maxThreads: 250
        uriEncoding: UTF-8
        compression: off
        compressableMimeTypes: application/json,text/json,application/xml,text/xml,text/plain
    use-forward-headers: false

---
security:
    headers:
        cache: false

---
